### ISSUE TITLE
Cannot generate PDF for a order >150€ (where the IOSS tax-thing isn't used anymore)

### ISSUE THREAD

**Issue by Dromantor** [Johennes/aliexpress-invoice-generator#3]
I ordered something with a total of ~280€ so the tax isn't collected by Aliexpress anymore since the IOSS limit is 150€. This seems to cause problems in your extension (I guess that's the reason).
I just get these errors directly on the page:
![grafik](https://user-images.githubusercontent.com/1822013/133737002-bd77cc68-23c6-4bd7-a446-1521e19c788a.png)
... and the console says:
![grafik](https://user-images.githubusercontent.com/1822013/133737135-937ec1db-4bd5-4a54-b3fa-ebf4d6d6ff2a.png)
... and no PDF output.

**Comment by Johennes** [comment]
Wow, thanks a lot for reporting this. I haven't encountered this case before. I have a fix for the null pointer exception in your screenshot but I'm not sure if there might be further issues after that as I don't know the specific layout of the AliExpress website in this case.

It would help a lot if you could save the website and send it to me via the feedback link in the add-on settings. However, I'd understand if you're not comfortable doing this. If so, please let me know. Then I'll just release the fix I have as a new version and if you find other issues afterwards, we can address them one by one with a new version release each.

**Comment by Dromantor** [comment]
I just scrambled all identifying data i could find and sent you the page.

**Comment by Johennes** [comment]
@Dromantor thanks again for filing this issue. I found a way to fix the null pointer exception and to also show the tax as negative in cases like this. I submitted version 3.1.2 for review for both Firefox and Chrome and it should be available within the next days.

**Comment by Dromantor** [comment]
You're welcome, thanks for the quick fix.
